begin;
select set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
do $$
declare owner_row public.users%rowtype; cfg public.daily_tea_config%rowtype; token text:=gen_random_uuid()::text; day date:=(now() at time zone 'Asia/Bangkok')::date;
 sid uuid; oid uuid; powder_before numeric; brewed_before numeric; n integer; result jsonb; retry jsonb; payload jsonb; ok boolean; staff_id uuid; other_branch uuid; staff_token text:=gen_random_uuid()::text; second_sid uuid;
begin
 select * into owner_row from public.users where role='owner' and is_active limit 1;
 insert into public.pin_sessions(user_id,token_hash) values(owner_row.id,encode(extensions.digest(token,'sha256'),'hex'));
 select * into cfg from public.daily_tea_config;
 select stock_qty into powder_before from public.ingredients where id=cfg.powder_id;
 select stock_qty into brewed_before from public.ingredients where id=cfg.brewed_id;
 insert into public.orders(order_no,client_uuid,branch_id,user_id,status,total,subtotal,discount,cogs_total) values('TEA-ROLLBACK-'||left(token,8),gen_random_uuid(),owner_row.branch_id,owner_row.id,'paid',0,0,0,0) returning id into oid;
 insert into public.stock_movements(ingredient_id,type,qty_delta,ref_order_id,user_id) values(cfg.brewed_id,'sale',-100,oid,owner_row.id);
 update public.ingredients set stock_qty=stock_qty-100 where id=cfg.brewed_id;
 insert into public.cash_sessions(branch_id,user_id,opening_cash) values(owner_row.branch_id,owner_row.id,0) returning id into sid;
 payload:=jsonb_build_object('session_id',sid,'counted_cash',0,'cups_sold',0,'note',null,'brewed_ml',600,'used_ml',100,'revision',0);
 -- Failure must not partially close the shift or settle tea.
 ok:=false;
 begin perform public.daily_tea_action(token,'close',payload||'{"brewed_ml":50}'); exception when others then ok:=true; end;
 assert ok,'insufficient batch accepted';
 assert (select closed_at is null from public.cash_sessions where id=sid),'failed close mutated session';
 assert not exists(select 1 from public.daily_tea_totals where business_date=day),'failed close created total';
 ok:=false;
 begin perform public.daily_tea_action(token,'close',payload||'{"counted_cash":-1}'); exception when others then ok:=true; end;
 assert ok,'invalid cash accepted';
 assert not exists(select 1 from public.daily_tea_totals where business_date=day),'cash failure partially settled tea';
 result:=public.daily_tea_action(token,'close',payload);
 assert (select waste_ml=500 and spoons=3 and powder_grams is null from public.daily_tea_totals where business_date=day),'wrong daily totals';
 assert (select stock_qty=powder_before from public.ingredients where id=cfg.powder_id),'unweighed powder was deducted';
 assert (select stock_qty=brewed_before from public.ingredients where id=cfg.brewed_id),'brewed balance incorrect';
 select count(*) into n from public.stock_movements;
 retry:=public.daily_tea_action(token,'close',payload);
 assert result=retry,'retry result differs';
 assert (select count(*)=n from public.stock_movements),'retry duplicated movement';
 ok:=false;
 begin perform public.daily_tea_action(token,'close',payload||'{"brewed_ml":1200}'); exception when others then ok:=true; end;
 assert ok,'changed retry accepted';
 perform public.daily_tea_action(token,'settings','{"grams_per_spoon":5}');
 assert (select stock_qty=powder_before-15 from public.ingredients where id=cfg.powder_id),'pending powder deduction incorrect';
 perform public.daily_tea_action(token,'settings','{"grams_per_spoon":5}');
 assert (select stock_qty=powder_before-15 from public.ingredients where id=cfg.powder_id),'settings duplicated deduction';
 -- A late sale must be visible and correcting waste restores only the daily delta.
 insert into public.stock_movements(ingredient_id,type,qty_delta,ref_order_id,user_id) values(cfg.brewed_id,'sale',-100,oid,owner_row.id);
 update public.ingredients set stock_qty=stock_qty-100 where id=cfg.brewed_id;
 assert (public.daily_tea_action(token,'load','{}')->>'used_ml')::numeric=200,'late sale absent';
 perform public.daily_tea_action(token,'revise',jsonb_build_object('date',day,'brewed_ml',600,'used_ml',200,'revision',1));
 assert (select stock_qty=brewed_before from public.ingredients where id=cfg.brewed_id),'late reconciliation balance incorrect';
 assert (select stock_qty=powder_before-15 from public.ingredients where id=cfg.powder_id),'revision recut powder';
 -- Voiding a sale reduces consumption and increases waste.
 update public.orders set status='void' where id=oid;
 update public.ingredients set stock_qty=stock_qty+200 where id=cfg.brewed_id;
 assert (public.daily_tea_action(token,'load','{}')->>'used_ml')::numeric=0,'void still counted';
 perform public.daily_tea_action(token,'revise',jsonb_build_object('date',day,'brewed_ml',600,'used_ml',0,'revision',2));
 assert (select stock_qty=brewed_before from public.ingredients where id=cfg.brewed_id),'void reconciliation incorrect';
 insert into public.branches(name) values('QA rollback branch') returning id into other_branch;
 insert into public.users(name,role,branch_id) values('QA rollback staff','staff',other_branch) returning id into staff_id;
 insert into public.pin_sessions(user_id,token_hash) values(staff_id,encode(extensions.digest(staff_token,'sha256'),'hex'));
 assert (public.daily_tea_action(staff_token,'load','{}')->>'used_ml')::numeric=0,'cross branch usage leaked';
 assert jsonb_array_length(public.daily_tea_action(staff_token,'load','{}')->'history')=0,'cross branch history leaked';
 assert (public.daily_tea_action(staff_token,'load','{}')->>'can_manage')::boolean,'staff controls hidden';
 perform public.daily_tea_action(staff_token,'settings','{"grams_per_spoon":5}');
 assert (select stock_qty=powder_before-15 from public.ingredients where id=cfg.powder_id),'staff settings duplicated deduction';
 ok:=false;
 begin perform public.daily_tea_action(staff_token,'close',payload); exception when others then ok:=true; end;
 assert ok,'staff closed another branch session';
 ok:=false;
 begin perform public.daily_tea_action('invalid-token','load','{}'); exception when others then ok:=true; end;
 assert ok,'invalid PIN accepted';
 insert into public.cash_sessions(branch_id,user_id,opening_cash,opened_at) values(owner_row.branch_id,owner_row.id,0,now()-interval '8 days') returning id into second_sid;
 perform public.daily_tea_action(token,'close',jsonb_build_object('session_id',second_sid,'counted_cash',0,'cups_sold',0,'note',null));
 assert (select closed_at is not null from public.cash_sessions where id=second_sid),'old shift cannot close';
 assert (select count(*)=1 from public.daily_tea_totals),'multiple shifts duplicated tea total';
 perform set_config('request.jwt.claim.sub','',true);
 ok:=false;
 begin perform public.daily_tea_action(token,'load','{}'); exception when others then ok:=true; end;
 assert ok,'anonymous auth accepted';
 assert not has_function_privilege('anon','public.daily_tea_action(text,text,jsonb)','execute'),'anon RPC grant';
 assert not has_table_privilege('authenticated','public.daily_tea_totals','select'),'direct table grant';
end $$;
select 'daily tea transaction checks passed; all fixture writes rolled back' as result;
rollback;
