-- Isolated fixture branches; every write (including settings/stock) is rolled back.
begin;
select set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
do $$
declare
 b uuid; other_b uuid; uid uuid; other_uid uuid; sid uuid;
 token text:=gen_random_uuid()::text; other_token text:=gen_random_uuid()::text;
 d date:=(now() at time zone 'Asia/Bangkok')::date;
 cfg public.daily_tea_config%rowtype; result jsonb; payload jsonb;
 before_powder numeric; after_powder numeric; n integer; rejected boolean;
begin
 insert into public.branches(name) values('QA tea staff rollback') returning id into b;
 insert into public.branches(name) values('QA tea other rollback') returning id into other_b;
 insert into public.users(name,role,branch_id) values('QA tea staff rollback','staff',b) returning id into uid;
 insert into public.users(name,role,branch_id) values('QA tea other rollback','staff',other_b) returning id into other_uid;
 insert into public.pin_sessions(user_id,token_hash) values(uid,encode(extensions.digest(token,'sha256'),'hex')),(other_uid,encode(extensions.digest(other_token,'sha256'),'hex'));
 result:=public.daily_tea_action(token,'load','{}');
 assert (result->>'can_manage')::boolean,'staff controls hidden';
 assert jsonb_array_length(result->'history')=0,'other branch history leaked';
 select * into cfg from public.daily_tea_config;
 perform public.daily_tea_action(token,'settings','{"grams_per_spoon":5}');
 assert (select grams_per_spoon=5 from public.daily_tea_config),'staff cannot save spoon weight';
 select stock_qty into before_powder from public.ingredients where id=cfg.powder_id;
 select count(*) into n from public.stock_movements;
 perform public.daily_tea_action(token,'settings','{"grams_per_spoon":5}');
 assert (select stock_qty=before_powder from public.ingredients where id=cfg.powder_id),'settings deducted twice';
 assert (select count(*)=n from public.stock_movements),'settings repeated movement';
 insert into public.cash_sessions(branch_id,user_id,opening_cash) values(b,uid,0) returning id into sid;
 payload:=jsonb_build_object('session_id',sid,'counted_cash',0,'cups_sold',0,'brewed_ml',600,'used_ml',0,'revision',0);
 perform public.daily_tea_action(token,'close',payload);
 assert (select brewed_ml=600 and powder_grams=15 from public.daily_tea_totals where branch_id=b and business_date=d),'staff close incorrect';
 select count(*) into n from public.stock_movements;
 perform public.daily_tea_action(token,'close',payload);
 assert (select count(*)=n from public.stock_movements),'close retry duplicated stock';
 result:=public.daily_tea_action(token,'revise',jsonb_build_object('date',d,'brewed_ml',800,'used_ml',0,'revision',1));
 assert (result->>'revision')::integer=2,'staff revision failed';
 assert (result->>'user_id')::uuid=uid,'staff attribution missing';
 assert (select stock_qty=before_powder-20 from public.ingredients where id=cfg.powder_id),'revision stock delta incorrect';
 assert exists(select 1 from private.daily_tea_audit where total_id=(result->>'id')::uuid),'revision audit missing';
 rejected:=false;
 begin perform public.daily_tea_action(token,'revise',jsonb_build_object('date',d,'brewed_ml',800,'used_ml',0,'revision',1)); exception when others then rejected:=true; end;
 assert rejected,'stale revision accepted';
 assert jsonb_array_length(public.daily_tea_action(other_token,'load','{}')->'history')=0,'other branch can read staff totals';
 rejected:=false;
 begin perform public.daily_tea_action(other_token,'close',payload); exception when others then rejected:=true; end;
 assert rejected,'other branch closed session';
 rejected:=false;
 begin perform public.daily_tea_action(token,'settings','{"grams_per_spoon":0}'); exception when others then rejected:=true; end;
 assert rejected,'zero spoon weight accepted';
 rejected:=false;
 begin perform public.daily_tea_action('invalid','settings','{"grams_per_spoon":5}'); exception when others then rejected:=true; end;
 assert rejected,'invalid PIN accepted';
 update public.users set is_active=false where id=uid;
 rejected:=false;
 begin perform public.daily_tea_action(token,'load','{}'); exception when others then rejected:=true; end;
 assert rejected,'inactive staff accepted';
 perform set_config('request.jwt.claim.sub','',true);
 rejected:=false;
 begin perform public.daily_tea_action(other_token,'load','{}'); exception when others then rejected:=true; end;
 assert rejected,'unauthenticated caller accepted';
 assert not has_function_privilege('anon','public.daily_tea_action(text,text,jsonb)','execute'),'anonymous RPC access';
 assert not has_table_privilege('authenticated','public.daily_tea_totals','update'),'direct total writes allowed';
end $$;
rollback;
select 'staff tea controls, settings, close, revision, idempotency, branch isolation and auth passed; fixtures rolled back' as result;
